//import { Inter } from "next/font/google";
import "./globals.css";
import { DM_Sans } from 'next/font/google'
import { Space_Mono } from 'next/font/google'
import { cn } from '@/lib/utils'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontHeading = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
  weight: '400', // You can specify the weight here if needed
})

const fontBody = Space_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
  weight: ['400', '700'], // Specify the weights you want to use
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(
          'antialiased',
          fontHeading.variable,
          fontBody.variable
        )}>{children}</body>
    </html>
  );
}
